markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: anlong2008.github.io
title: An Long's Blog
description: 
author: An Long
email: winfirm#163.com
github: anlong2008

config:
  js_dir:
  img_dir:
  css_dir:
